version: "3"

services:
  shiva:
    image: aum-shiva
    build:
      dockerfile: Dockerfile-dev
      context: ../shiva
    volumes:
      - $GOPATH:/go:ro
      - ../shiva:/go/src/github.com/artificial-universe-maker/shiva:ro
    ports:
      - 8000:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  lakshmi:
    image: aum-lakshmi-dev
    build:
      context: ../lakshmi
      dockerfile: Dockerfile-dev
    volumes:
      - $GOPATH:/go:ro
      - ../lakshmi:/go/src/github.com/artificial-universe-maker/lakshmi:ro
    ports:
      - 8042:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  brahman:
    image: aum-brahman-dev
    build:
      context: ../brahman
      dockerfile: Dockerfile-dev
    volumes:
      - $GOPATH:/go:ro
      - ../brahman:/go/src/github.com/artificial-universe-maker/brahman:ro
    ports:
      - 9001:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  postgres:
    image: postgres
    ports:
      - 5432:5432
  adminer:
      image: adminer
      ports:
          - 8001:8080
  ganesha:
    image: aum-ganesha
    build:
      dockerfile: Dockerfile-dev
      context: ../ganesha
    volumes:
      - $GOPATH:/go:ro
      - ../ganesha:/go/src/github.com/artificial-universe-maker/ganesha:ro
    ports:
      - 9002:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6380:6379