version: "3"

services:
  kalidasa:
    image: talkative-kalidasa-dev
    build:
      dockerfile: dev.Dockerfile
      context: $TALKATIVEPATH/kalidasa
    ports:
      - 8043:8080
    depends_on:
      - "redis"
  vishnu:
    image: talkative-vishnu-dev
    build:
      dockerfile: dev.Dockerfile
      context: $TALKATIVEPATH/vishnu
    ports:
      - 9002:8080
    volumes:
      - $TALKATIVEPATH/vishnu:/main:ro
  shiva:
    image: talkative-shiva-dev
    build:
      dockerfile: Dockerfile-dev
      context: ../shiva
    volumes:
      - $GOPATH:/go:ro
      - ../shiva:/go/src/github.com/talkative-ai/shiva:ro
    ports:
      - 8000:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  lakshmi:
    image: talkative-lakshmi-dev
    build:
      context: ../lakshmi
      dockerfile: Dockerfile-dev
    volumes:
      - $GOPATH:/go:ro
      - ../lakshmi:/go/src/github.com/talkative-ai/lakshmi:ro
    ports:
      - 8042:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  brahman:
    image: talkative-brahman-dev
    build:
      context: ../brahman
      dockerfile: Dockerfile-dev
    volumes:
      - $GOPATH:/go:ro
      - ../brahman:/go/src/github.com/talkative-ai/brahman:ro
    ports:
      - 9001:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  postgres:
    image: postgres
    ports:
      - 5432:5432
  adminer:
      image: adminer
      ports:
          - 8001:8080
  ganesha:
    image: talkative-ganesha-dev
    build:
      dockerfile: Dockerfile-dev
      context: ../ganesha
    volumes:
      - $GOPATH:/go:ro
      - ../ganesha:/go/src/github.com/talkative-ai/ganesha:ro
    ports:
      - 10000:8080
    depends_on:
      - "postgres"
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6380:6379